"""
Company registry — canonical display names and default approval windows.
"""

# Type alias: duration in hours, or the MIDNIGHT sentinel, or None (no default).
_Hours = float | str | None

# Sentinel: resolve to however many hours remain until 23:59 IST at call time.
MIDNIGHT = "MIDNIGHT"
FOOD = 2.0  # Restaurant / food delivery (Zomato, Swiggy, Dominos …)
QUICK = 1.0  # Quick commerce / 10-min delivery (Zepto, Blinkit, Instamart …)


# Canonical display names sent to the API for known companies.
# Keys must match the normalised form used in KNOWN_COMPANIES (lowercase, no
# spaces/hyphens/underscores).
COMPANY_DISPLAY_NAMES: dict[str, str] = {
    # Confirmed live against the API 2026-09-04: the resident app's own "any
    # company" pre-approval sends the literal company string "Any" (not a
    # blank/empty string — that's accepted too, but renders as a nameless
    # entry rather than the app's own generic option).
    "any": "Any",
    "zepto": "Zepto",
    "blinkit": "Blinkit",
    "swiggy": "Swiggy",
    "swiggyinstamart": "Swiggy Instamart",
    "swiggygenie": "Swiggy Genie",
    "swiggyfood": "Swiggy Food",
    "instamart": "Instamart",
    "snacc": "Snacc",
    "zomato": "Zomato",
    "handpickd": "Handpickd",
    "oladash": "Ola Dash",
    "pickily": "Pickily",
    "box8": "Box8",
    "licious": "Licious",
    "eatsure": "EatSure",
    "eatfit": "EatFit",
    "freshmenu": "FreshMenu",
    "foodpanda": "Foodpanda",
    "faasos": "Faasos",
    "fassos": "Fassos",
    "deliveroo": "Deliveroo",
    "bigbasketbbnow": "BigBasket BB Now",
    "bigbasketbbinstant": "BigBasket BB Instant",
    "flipkartminutes": "Flipkart Minutes",
    "dunzogrocery": "Dunzo Grocery",
    "dunzopetsupplies": "Dunzo Pet Supplies",
    "dunzomedicines": "Dunzo Medicines",
    "amazon": "Amazon",
    "amazonfresh": "Amazon Fresh",
    "amazondelivery": "Amazon Delivery",
    "amazonfoods": "Amazon Foods",
    "flipkart": "Flipkart",
    "flipkartdelivery": "Flipkart Delivery",
    "flipkartgrocery": "Flipkart Grocery",
    "myntra": "Myntra",
    "snapdeal": "Snapdeal",
    "jabong": "Jabong",
    "tatacliq": "Tata CLiQ",
    "firstcry": "FirstCry",
    "firstclub": "FirstClub",
    "lenskart": "Lenskart",
    "decathlon": "Decathlon",
    "shopclues": "ShopClues",
    "bigbasket": "BigBasket",
    "bigbasketbbdaily": "BigBasket BB Daily",
    "bigbasketfresho": "BigBasket Fresho",
    "jiomart": "JioMart",
    "jiomartgrocery": "JioMart Grocery",
    "jiomartelectronics": "JioMart Electronics",
    "milkbasket": "Milkbasket",
    "freshtohome": "FreshToHome",
    "countrydelight": "Country Delight",
    "doodhwala": "Doodhwala",
    "otipy": "Otipy",
    "sardafarms": "Sarda Farms",
    "dmart": "DMart",
    "naturesbasket": "Nature's Basket",
    "grandcitysupermarket": "Grand City Supermarket",
    "theorganicworld": "The Organic World",
    "sansar": "Sansar",
    "mangohypermarket": "Mango Hypermarket",
    "milkvilla": "Milkvilla",
    "delhivery": "Delhivery",
    "bluedart": "Blue Dart",
    "xpressbees": "Xpressbees",
    "shadowfax": "Shadowfax",
    "dtdc": "DTDC",
    "porter": "Porter",
    "gati": "Gati",
    "safeexpress": "Safeexpress",
    "dhl": "DHL",
    "dninja": "DNinja",
    "fedex": "FedEx",
    "indiapost": "India Post",
    "dunzocourier": "Dunzo Courier",
    "pharmeasy": "PharmEasy",
    "tata1mg": "Tata 1mg",
    "netmeds": "Netmeds",
    "apollopharmacy": "Apollo Pharmacy",
    "dominos": "Dominos",
    "pizzahut": "Pizza Hut",
    "ovenstorypizza": "Oven Story Pizza",
    "urbancompany": "Urban Company",
    "urbancompanyacservicerepair": "Urban Company AC Service Repair",
    "urbancompanyhomecleaning": "Urban Company Home Cleaning",
    "urbancompanyhomepainting": "Urban Company Home Painting",
    "urbancompanyplumbingcarpenter": "Urban Company Plumbing Carpenter",
    "urbancompanybathroomkitchencleaning": "Urban Company Bathroom Kitchen Cleaning",
    "urbancompanyelectrician": "Urban Company Electrician",
    "urbancompanyhairoutbeauty": "Urban Company Hairout Beauty",
    "yesmadam": "Yes Madam",
    "indane": "Indane",
    "hpgas": "HP Gas",
    "bharathgas": "Bharath Gas",
    "gail": "GAIL",
    "gailgas": "GAIL Gas",
    "livspace": "Livspace",
    "homelane": "HomeLane",
    "bonito": "Bonito",
    "designcafe": "Design Cafe",
    "insanelygood": "InsanelyGood",
    "suprdaily": "SuprDaily",
    "dunzo": "Dunzo",
}


# Well-known delivery companies with their default window durations (hours).
# None means the company is recognised but has no sensible default — the caller
# must supply an explicit duration.
KNOWN_COMPANIES: dict[str, _Hours] = {
    # ── Generic "any company" pre-approval (1 h) ────────────────────────────
    # Not brand-specific — lets any delivery/visitor through under one entry.
    "any": QUICK,
    # ── Quick commerce / 10-min delivery (1 h) ─────────────────────────────
    "zepto": QUICK,
    "blinkit": QUICK,
    "swiggyinstamart": QUICK,
    "swiggyfood": QUICK,  # API child id
    "instamart": QUICK,
    "snacc": QUICK,
    "oladash": QUICK,
    "bigbasketbbnow": QUICK,
    "bigbasketbbinstant": QUICK,
    "flipkartminutes": QUICK,
    "dunzogrocery": QUICK,
    "dunzopetsupplies": QUICK,
    "dunzomedicines": QUICK,
    # ── Food / restaurant delivery (2 h) ────────────────────────────────────
    "swiggy": FOOD,
    "swiggygenie": FOOD,
    "zomato": FOOD,
    "dominos": FOOD,
    "pizzahut": FOOD,
    "ovenstorypizza": FOOD,
    "handpickd": FOOD,
    "pickily": FOOD,
    "box8": FOOD,
    "licious": FOOD,
    "eatsure": FOOD,
    "eatfit": FOOD,
    "freshmenu": FOOD,
    "foodpanda": FOOD,
    "faasos": FOOD,
    "fassos": FOOD,  # API id spelling
    "deliveroo": FOOD,
    # ── Everything else — open till midnight ─────────────────────────────────
    # E-commerce
    "amazon": MIDNIGHT,
    "amazonfresh": MIDNIGHT,
    "amazondelivery": MIDNIGHT,
    "amazonfoods": MIDNIGHT,
    "flipkart": MIDNIGHT,
    "flipkartdelivery": MIDNIGHT,
    "flipkartgrocery": MIDNIGHT,
    "myntra": MIDNIGHT,
    "snapdeal": MIDNIGHT,
    "jabong": MIDNIGHT,
    "tatacliq": MIDNIGHT,
    "firstcry": MIDNIGHT,
    "firstclub": MIDNIGHT,
    "lenskart": MIDNIGHT,
    "decathlon": MIDNIGHT,
    "shopclues": MIDNIGHT,
    # Grocery / pharmacy / milk
    "bigbasket": MIDNIGHT,
    "bigbasketbbdaily": MIDNIGHT,
    "bigbasketfresho": MIDNIGHT,
    "jiomart": MIDNIGHT,
    "jiomartgrocery": MIDNIGHT,
    "jiomartelectronics": MIDNIGHT,
    "milkbasket": MIDNIGHT,
    "freshtohome": MIDNIGHT,
    "countrydelight": MIDNIGHT,
    "doodhwala": MIDNIGHT,
    "otipy": MIDNIGHT,
    "sardafarms": MIDNIGHT,
    "dmart": MIDNIGHT,
    "naturesbasket": MIDNIGHT,
    "grandcitysupermarket": MIDNIGHT,
    "theorganicworld": MIDNIGHT,
    "sansar": MIDNIGHT,
    "mangohypermarket": MIDNIGHT,
    "milkvilla": MIDNIGHT,
    "pharmeasy": MIDNIGHT,
    "tata1mg": MIDNIGHT,
    "netmeds": MIDNIGHT,
    "apollopharmacy": MIDNIGHT,
    # Couriers
    "delhivery": MIDNIGHT,
    "bluedart": MIDNIGHT,
    "xpressbees": MIDNIGHT,
    "shadowfax": MIDNIGHT,
    "dtdc": MIDNIGHT,
    "porter": MIDNIGHT,
    "gati": MIDNIGHT,
    "safeexpress": MIDNIGHT,
    "dhl": MIDNIGHT,
    "dninja": MIDNIGHT,
    "fedex": MIDNIGHT,
    "indiapost": MIDNIGHT,
    "dunzocourier": MIDNIGHT,
    # Home services
    "urbancompany": MIDNIGHT,
    "urbancompanyacservicerepair": MIDNIGHT,
    "urbancompanyhomecleaning": MIDNIGHT,
    "urbancompanyhomepainting": MIDNIGHT,
    "urbancompanyplumbingcarpenter": MIDNIGHT,
    "urbancompanybathroomkitchencleaning": MIDNIGHT,
    "urbancompanyelectrician": MIDNIGHT,
    "urbancompanyhairoutbeauty": MIDNIGHT,
    "yesmadam": MIDNIGHT,
    # ── No sensible default — caller must supply --hours ──────────────────────
    "indane": None,
    "hpgas": None,
    "bharathgas": None,
    "gail": None,
    "gailgas": None,
    "livspace": None,
    "homelane": None,
    "bonito": None,
    "designcafe": None,
    "insanelygood": None,  # SuprDaily — scheduled subscription
    "suprdaily": None,
    "dunzo": None,  # parent entry; sub-types have defaults above
}
